all DZ-3
Otus-DevOps-2023-09/dokshinda_infra pull request #3
Opened 2023-11-06 13:38 UTC by dokshinda

# Выполнено ДЗ №3 (прошу проверить быстрей на облаке осталось мало денег на балансе)

2023-11-07 10:03 UTC, dokshinda commented
Там пароль стоит на ключ beromint33 возможно поэтому не проходит тест

2023-11-07 20:16 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
В ридми нужно добавить адреса для бастион хоста и для внутреннего хоста
Сделать это надо так же как указано в методичке
ДЗ возвращаю на доработку

2023-11-08 06:10 UTC, dokshinda commented
исправил

2023-11-08 19:59 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-11-09 05:31 UTC, merged